name: Build and Deploy to Artifactory

on:
  push:
    branches:
      - main
  schedule:
    # Runs at 00:00 UTC every day
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Specify the Java distribution
          java-version: '11'

      - name: Set up Gradle
        uses: actions/setup-java@v3
        with:
          distribution: gradle
          java-version: 11  # Specify the Java version to use with Gradle
          gradle-version: 6.8.3

      - name: Build with Gradle
        run: ./gradlew build

      - name: Deploy to Artifactory
        env:
          ARTIFACTORY_URL: ${{ secrets.JF_URL }}
          ARTIFACTORY_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
        run: |
          ./gradlew publish -Purl=${{ secrets.JF_URL }}/your-repo -PapiKey=${{ secrets.JF_ACCESS_TOKEN  }}




